"""initial auth models

Revision ID: 2bd01eebec0c
Revises: 
Create Date: 2025-12-16 04:37:36.683703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bd01eebec0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_classes_teacher'))

    # op.drop_table('classes')
    # with op.batch_alter_table('grades', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idx_grades_student'))
    #     batch_op.drop_index(batch_op.f('idx_grades_subject'))

    # op.drop_table('grades')
    # with op.batch_alter_table('subjects', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idx_subjects_class'))

    # op.drop_table('subjects')
    # with op.batch_alter_table('students', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idx_students_class'))

    # op.drop_table('students')
    # with op.batch_alter_table('attendance', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idx_attendance_date'))
    #     batch_op.drop_index(batch_op.f('idx_attendance_student'))

    # op.drop_table('attendance')
    # with op.batch_alter_table('timetable', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idx_timetable_class'))
    #     batch_op.drop_index(batch_op.f('idx_timetable_day'))

    # op.drop_table('timetable')
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
    #     batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
    #     batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
    #     batch_op.alter_column('email',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=120),
    #            existing_nullable=False)
    #     batch_op.alter_column('password_hash',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=255),
    #            existing_nullable=False)
    #     batch_op.alter_column('id',
    #            existing_type=sa.UUID(),
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True,
    #            existing_server_default=sa.text('uuid_generate_v4()'))
    #     batch_op.alter_column('created_at',
    #            existing_type=postgresql.TIMESTAMP(timezone=True),
    #            type_=sa.DateTime(),
    #            existing_nullable=True,
    #            existing_server_default=sa.text('now()'))
    #     batch_op.drop_index(batch_op.f('idx_users_role'))
    #     batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])
    #     batch_op.drop_column('full_name')
    #     batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.TEXT(), server_default=sa.text("'teacher'::text"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_users_role'), ['role'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('uuid_generate_v4()'))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('role_id')

    op.create_table('timetable',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('day_of_week', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("day_of_week = ANY (ARRAY['Monday'::text, 'Tuesday'::text, 'Wednesday'::text, 'Thursday'::text, 'Friday'::text, 'Saturday'::text])", name=op.f('timetable_day_of_week_check')),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('timetable_class_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('timetable_subject_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('timetable_pkey'))
    )
    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_timetable_day'), ['day_of_week'], unique=False)
        batch_op.create_index(batch_op.f('idx_timetable_class'), ['class_id'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('marked_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status = ANY (ARRAY['present'::text, 'absent'::text, 'leave'::text])", name=op.f('attendance_status_check')),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], name=op.f('attendance_marked_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('attendance_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_pkey')),
    sa.UniqueConstraint('student_id', 'date', name=op.f('attendance_student_id_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_attendance_student'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendance_date'), ['date'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('roll_no', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('parent_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parent_contact', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='students_class_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='students_pkey'),
    sa.UniqueConstraint('roll_no', 'class_id', name='students_roll_no_class_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_students_class'), ['class_id'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('subject_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='subjects_class_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subjects_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_subjects_class'), ['class_id'], unique=False)

    op.create_table('grades',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('marks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exam_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('grades_student_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('grades_subject_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('grades_pkey')),
    sa.UniqueConstraint('student_id', 'subject_id', 'exam_type', name=op.f('grades_student_id_subject_id_exam_type_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_grades_subject'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_grades_student'), ['student_id'], unique=False)

    op.create_table('classes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('class_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('classes_teacher_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('classes_pkey'))
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_classes_teacher'), ['teacher_id'], unique=False)

    op.drop_table('roles')
    # ### end Alembic commands ###
